apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: learning-engine-backend-data
  namespace: learning-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
